# Use RPATH on OS X
if(APPLE)
  set(CMAKE_MACOSX_RPATH ON)
endif()

macro(add_rpath)
  list(REMOVE_DUPLICATES DEPENDENCY_LIBRARY_DIRS)
  set(CMAKE_INSTALL_RPATH "${DEPENDENCY_LIBRARY_DIRS}")
  set(CMAKE_BUILD_RPATH "${DEPENDENCY_LIBRARY_DIRS}")
  set(CMAKE_SKIP_BUILD_RPATH OFF)
  set(CMAKE_BUILD_WITH_INSTALL_RPATH ON)
  set(CMAKE_INSTALL_RPATH_USE_LINK_PATH ON)
endmacro()
