name: CI

on:
  push:
    branches: [ main, develop, initialize ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    env:
      CMAKE_POLICY_VERSION_MINIMUM: 3.5

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04, ubuntu-latest, macos-latest]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies (Ubuntu)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake lcov zlib1g-dev libsqlite3-dev pkg-config
    
    - name: Install dependencies (macOS)
      if: runner.os == 'macOS'
      run: |
        brew install cmake lcov zlib sqlite pkg-config

    - name: Run test + coverage
      if: matrix.os == 'ubuntu-24.04'
      run: |
        make coverage

    - name: Run test (Unix)
      if: runner.os != 'Windows' && matrix.os != 'ubuntu-24.04'
      run: |
        make test
    
    - name: Upload coverage reports to Codecov (Unix)
      if: matrix.os == 'ubuntu-24.04'
      uses: codecov/codecov-action@v4
      with:
        file: build-coverage/coverage/coverage_filtered.info
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false
        verbose: true
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
